### ISSUE TITLE
Assembler doesn't recognize shifts with registers

### ISSUE THREAD

**Issue by mrRosset** [mgard/epater#1]
Hello,

As said in the title, the assembler produce errors when trying to any data processing instruction that has a shift with the amount being specified as a register.

I can't find anything about this in the unimplemented instructions part of the readme or in the [manual v2](http://vision.gel.ulaval.ca/~jflalonde/cours/1001/h17/docs/manuel-simulateurARM.pdf). So I assume it's a bug.

Minimal reproduction:
```asm
SECTION INTVEC

B main


SECTION CODE

main
MOV R12, R4, ROR #12
MOV R1, R0, LSR R4

SECTION DATA
```

The assembler complains about the second instruction "Impossible d'interpréter l'instruction" but is fine with the first one.

Thanks a lot

**Comment by mgard** [comment]
Thanks for the report. You are absolutely right, this kind of shift should be working and is not. Also, the pseudo instruction form (like LSL R1, R2, R3) is working so it is definitely an issue with the parser. At this moment, I am not exactly sure which ill-formed yacc rule is causing this, but this will be fixed. I'll also add a unit test covering this use case to avoid further repetitions of this bug.

Currently, I am away from my computer and cannot easily fix such a bug, but I will do once I get back home.

Thanks again for your report; on another topic, I am sorry for the French text, we envision to internationalize the simulator at some point!

**Comment by mrRosset** [comment]
Thank you.

> on another topic, I am sorry for the French text, we envision to internationalize the simulator at some point!

I'm a native french speaker so it's not a problem for me. I used english here since it's what you are using in the Readme.

**Comment by mgard** [comment]
Sorry for the delay, I finally had the time to look at this. The issue should be fixed [this commit](https://github.com/mgard/epater/commit/aea990f9fc23a529e63700e613d3c717444a5c50). I leave the issue open for now to remind me to add such test case to our test suite.

Do not hesitate to post any other related problem here!

**Comment by mgard** [comment]
Commit 99817d18ed fix this, (finally) closing the issue. Thanks for the report!
