### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by patoch01220** [mgard/epater#14]
Hey,
i need to code in ARM for my studies and i am trying to install Epater. 
When i run the command python mainweb.py DEBUG " 
i got an error in the mainweb.py line 39 saying that the file emaipass.txt deon't exist, and i don't have that file. what should i do ? 
Thank you ^^

**Comment by mgard** [comment]
Should be fixed in 8c0726ae783ebbe452371b26a348c6b4c4dec3d9 
This is just a email notification system we use in production, it is indeed not needed for local execution.
